"""W3C PROV-O provenance tracking module.

Creates PROV-O compliant provenance documents that track the generation
of 3D models and rendered images, including entities, activities, agents,
timestamps, and generation parameters. Supports export to PROV-JSON and PROV-XML.
"""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

from prov.model import ProvDocument, Namespace, PROV_TYPE

logger = logging.getLogger(__name__)


class ProvenanceTracker:
    """Tracks provenance for 3D object generation using W3C PROV-O.

    Attributes:
        doc: The PROV document being constructed.
    """

    def __init__(self, project_name: str = "3DProvenance") -> None:
        """Initialize the provenance tracker.

        Args:
            project_name: Name used for the project namespace.
        """
        self.doc = ProvDocument()
        self._ns = Namespace("proj", f"http://example.org/{project_name}/")
        self.doc.add_namespace(self._ns)
        self.doc.add_namespace("prov", "http://www.w3.org/ns/prov#")
        self.doc.add_namespace("xsd", "http://www.w3.org/2001/XMLSchema#")
        self._start_time: Optional[datetime] = None
        self._end_time: Optional[datetime] = None
        logger.info("ProvenanceTracker initialized for project '%s'", project_name)

    def record_activity(
        self,
        activity_id: str,
        description: str,
        parameters: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Record a generation activity with optional parameters.

        Args:
            activity_id: Unique identifier for the activity.
            description: Human-readable description of the activity.
            parameters: Dictionary of generation parameters to record.
        """
        self._start_time = datetime.now(timezone.utc)
        attrs = {
            "prov:label": description,
        }
        if parameters:
            for key, value in parameters.items():
                attrs[self._ns[f"param_{key}"]] = str(value)

        self.doc.activity(
            self._ns[activity_id],
            self._start_time,
            other_attributes=attrs,
        )
        logger.info("Recorded activity: %s", activity_id)

    def record_entity(
        self,
        entity_id: str,
        entity_type: str,
        filepath: str,
        attributes: Optional[Dict[str, str]] = None,
    ) -> None:
        """Record an entity (3D model or rendered image).

        Args:
            entity_id: Unique identifier for the entity.
            entity_type: Type of entity (e.g., '3DModel', 'RenderedImage').
            filepath: File path where the entity is stored.
            attributes: Additional attributes to record.
        """
        attrs: Dict[Any, Any] = {
            PROV_TYPE: self._ns[entity_type],
            "prov:label": entity_id,
            self._ns["filepath"]: filepath,
        }
        if attributes:
            for key, value in attributes.items():
                attrs[self._ns[key]] = value

        self.doc.entity(self._ns[entity_id], attrs)
        logger.info("Recorded entity: %s (%s)", entity_id, entity_type)

    def record_agent(
        self,
        agent_id: str,
        software_name: str,
        version: str,
    ) -> None:
        """Record a software agent.

        Args:
            agent_id: Unique identifier for the agent.
            software_name: Name of the software.
            version: Software version string.
        """
        self.doc.agent(
            self._ns[agent_id],
            {
                PROV_TYPE: "prov:SoftwareAgent",
                "prov:label": software_name,
                self._ns["version"]: version,
            },
        )
        logger.info("Recorded agent: %s v%s", software_name, version)

    def record_generation(
        self, entity_id: str, activity_id: str
    ) -> None:
        """Record that an entity was generated by an activity.

        Args:
            entity_id: Identifier of the generated entity.
            activity_id: Identifier of the generating activity.
        """
        self._end_time = datetime.now(timezone.utc)
        self.doc.wasGeneratedBy(
            self._ns[entity_id],
            self._ns[activity_id],
            self._end_time,
        )
        logger.debug("Recorded generation: %s by %s", entity_id, activity_id)

    def record_attribution(self, entity_id: str, agent_id: str) -> None:
        """Record that an entity was attributed to an agent.

        Args:
            entity_id: Identifier of the entity.
            agent_id: Identifier of the agent.
        """
        self.doc.wasAttributedTo(self._ns[entity_id], self._ns[agent_id])
        logger.debug("Recorded attribution: %s to %s", entity_id, agent_id)

    def record_derivation(
        self, derived_id: str, source_id: str
    ) -> None:
        """Record that an entity was derived from another entity.

        Args:
            derived_id: Identifier of the derived entity.
            source_id: Identifier of the source entity.
        """
        self.doc.wasDerivedFrom(self._ns[derived_id], self._ns[source_id])
        logger.debug("Recorded derivation: %s from %s", derived_id, source_id)

    def export_json(self, filepath: str) -> str:
        """Export the provenance document as PROV-JSON.

        Args:
            filepath: Output file path (without extension).

        Returns:
            The full path of the exported JSON file.
        """
        output_path = Path(filepath).with_suffix(".json")
        output_path.parent.mkdir(parents=True, exist_ok=True)

        prov_json = self.doc.serialize(format="json")
        parsed = json.loads(prov_json)
        output_path.write_text(
            json.dumps(parsed, indent=2, default=str), encoding="utf-8"
        )
        logger.info("Exported provenance JSON to %s", output_path)
        return str(output_path)

    def export_xml(self, filepath: str) -> str:
        """Export the provenance document as PROV-XML.

        Args:
            filepath: Output file path (without extension).

        Returns:
            The full path of the exported XML file.
        """
        output_path = Path(filepath).with_suffix(".xml")
        output_path.parent.mkdir(parents=True, exist_ok=True)

        prov_xml = self.doc.serialize(format="xml")
        if isinstance(prov_xml, str):
            output_path.write_text(prov_xml, encoding="utf-8")
        else:
            output_path.write_bytes(prov_xml)
        logger.info("Exported provenance XML to %s", output_path)
        return str(output_path)

    def get_document(self) -> ProvDocument:
        """Return the underlying PROV document.

        Returns:
            The PROV document.
        """
        return self.doc
